server:
  port: 7000

spring:
  application:
    name: micr-dataservice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ylb
    username: root
    password: 123456.

  redis:
    database: 10
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.xwh.dataservice.service
  provider:
    timeout: 50000
    retries: 0

